#!/bin/bash -eu

. debian/debian.env

# We only build the lowlatency/lowlatency-64k flavours
sed -i '/^flavours.*$/d' ${DEBIAN}/rules.d/amd64.mk
sed -i '/^flavours.*$/d' ${DEBIAN}/rules.d/arm64.mk
echo -e "flavours\t= lowlatency" >> ${DEBIAN}/rules.d/amd64.mk
echo -e "flavours\t= lowlatency lowlatency-64k" >> ${DEBIAN}/rules.d/arm64.mk

# We only care about lowlatency/lowlatency-64k abis
sed -i /getall/d ${DEBIAN}/etc/getabis
echo "getall amd64 lowlatency" >> ${DEBIAN}/etc/getabis
echo "getall arm64 lowlatency lowlatency-64k" >> ${DEBIAN}/etc/getabis

# Override options in rules.d/hooks.mk (normally master does not have this
# file but it got added for generic annotations enforcement.
cat <<EOD >>${DEBIAN}/rules.d/hooks.mk
do_libc_dev_package	= false
do_doc_package		= false
do_tools_common		= false
do_tools_host		= false
EOD
